// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6kFVqGH0CCWCDX_ruenyDrFx9xBw-3OY',
    appId: '1:1026298511220:web:654ae7bf011933a0bd7621',
    messagingSenderId: '1026298511220',
    projectId: 'expense-ee801',
    authDomain: 'expense-ee801.firebaseapp.com',
    storageBucket: 'expense-ee801.firebasestorage.app',
    measurementId: 'G-GDZ4SZPFRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kFVqGH0CCWCDX_ruenyDrFx9xBw-3OY',
    appId: '1:1026298511220:android:ef27b0b98f1892d6bd7621',
    messagingSenderId: '1026298511220',
    projectId: 'expense-ee801',
    storageBucket: 'expense-ee801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6AByvV5o0w8j4CHYot8DNcag55ZZuTGg',
    appId: '1:1026298511220:ios:7594423767c1dce3bd7621',
    messagingSenderId: '1026298511220',
    projectId: 'expense-ee801',
    storageBucket: 'expense-ee801.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6AByvV5o0w8j4CHYot8DNcag55ZZuTGg',
    appId: '1:1026298511220:ios:7594423767c1dce3bd7621',
    messagingSenderId: '1026298511220',
    projectId: 'expense-ee801',
    storageBucket: 'expense-ee801.firebasestorage.app',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjrk3YxCUfDidpEPDOvSWB66fmyW8FcXo',
    appId: '1:1026298511220:web:da3382bcced5cd38bd7621',
    messagingSenderId: '1026298511220',
    projectId: 'expense-ee801',
    authDomain: 'expense-ee801.firebaseapp.com',
    storageBucket: 'expense-ee801.firebasestorage.app',
    measurementId: 'G-Q7CMB66H6R',
  );

}